execute @p[r=1,tag=cabelo_naruto] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_2] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_2_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_3] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_3_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_4] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_4_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_2] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_2_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_3] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_3_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_4] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_4_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_kakashi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:kakashi_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_jiraiya] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:jiraya_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_pain] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:pain_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_deidara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:deidara_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_itachi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:itachi_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_madara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:madara_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:hinata_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_neji] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:neji_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_rocklee] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:rocklee_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tenten] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tenten_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_temari] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:temari_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_gaara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:gaara_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobirama] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tobirama_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_boruto] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:boruto_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_mitsuki] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:mitsuki_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tobi_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}

execute @p[r=1,tag=cabelo_sakura] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sakura_laranja 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}