execute @p[r=1,tag=cabelo_naruto] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_2] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_2_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_3] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_3_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_4] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:naruto_4_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_2] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_2_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_3] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_3_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_4] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sasuke_4_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_kakashi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:kakashi_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_jiraiya] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:jiraya_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_pain] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:pain_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_deidara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:deidara_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_itachi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:itachi_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_madara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:madara_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:hinata_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_neji] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:neji_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_rocklee] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:rocklee_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tenten] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tenten_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_temari] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:temari_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_gaara] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:gaara_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobirama] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tobirama_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_boruto] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:boruto_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_mitsuki] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:mitsuki_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobi] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:tobi_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}

execute @p[r=1,tag=cabelo_sakura] ~~~ replaceitem entity @e[type=porkyn:clone,r=5] slot.armor.feet 1 hair:sakura_azul_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}