tag @s add fogo
tag @s add agua
tag @s add vento
tag @s add raio
tag @s add terra
tag @s add areia
tag @s add areia_ferro
tag @s add gelo
tag @s add lava
tag @s add madeira
tag @s add vapor
tag @s add cristal
tag @s add lama
tag @s add tempestade