execute @p[r=1,tag=cabelo_naruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_2_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_3_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_4_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_2_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_3_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_4_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_kakashi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:kakashi_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_jiraiya] ~~~ replaceitem entity @p slot.armor.feet 1 hair:jiraya_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_pain] ~~~ replaceitem entity @p slot.armor.feet 1 hair:pain_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_deidara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:deidara_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_itachi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:itachi_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_madara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:madara_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_neji] ~~~ replaceitem entity @p slot.armor.feet 1 hair:neji_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_rocklee] ~~~ replaceitem entity @p slot.armor.feet 1 hair:rocklee_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tenten] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tenten_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_temari] ~~~ replaceitem entity @p slot.armor.feet 1 hair:temari_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_gaara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:gaara_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobirama] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobirama_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_boruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:boruto_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_mitsuki] ~~~ replaceitem entity @p slot.armor.feet 1 hair:mitsuki_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobi_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
dialogue open @s @p cor_rosa_c"
execute @p[r=1,tag=cabelo_sakura] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sakura_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_rosa_c_2 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_anko] ~~~ replaceitem entity @p slot.armor.feet 1 hair:anko_rosa_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}