execute @p[r=1,tag=cabelo_naruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_2_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_3_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_4_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_2_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_3_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_4_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_kakashi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:kakashi_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_jiraiya] ~~~ replaceitem entity @p slot.armor.feet 1 hair:jiraya_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_pain] ~~~ replaceitem entity @p slot.armor.feet 1 hair:pain_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_deidara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:deidara_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_itachi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:itachi_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_madara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:madara_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_neji] ~~~ replaceitem entity @p slot.armor.feet 1 hair:neji_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_rocklee] ~~~ replaceitem entity @p slot.armor.feet 1 hair:rocklee_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tenten] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tenten_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_temari] ~~~ replaceitem entity @p slot.armor.feet 1 hair:temari_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_gaara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:gaara_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobirama] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobirama_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_boruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:boruto_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_mitsuki] ~~~ replaceitem entity @p slot.armor.feet 1 hair:mitsuki_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobi_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
dialogue open @s @p cor_verde_c"
execute @p[r=1,tag=cabelo_sakura] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sakura_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_verde_c_2 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_anko] ~~~ replaceitem entity @p slot.armor.feet 1 hair:anko_verde_c 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}