execute @p[r=1,tag=cabelo_naruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_2_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_3_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_naruto_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:naruto_4_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_2_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_3] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_3_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_sasuke_4] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sasuke_4_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_kakashi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:kakashi_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_jiraiya] ~~~ replaceitem entity @p slot.armor.feet 1 hair:jiraya_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_pain] ~~~ replaceitem entity @p slot.armor.feet 1 hair:pain_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_deidara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:deidara_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_itachi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:itachi_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_madara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:madara_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_neji] ~~~ replaceitem entity @p slot.armor.feet 1 hair:neji_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_rocklee] ~~~ replaceitem entity @p slot.armor.feet 1 hair:rocklee_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tenten] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tenten_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_temari] ~~~ replaceitem entity @p slot.armor.feet 1 hair:temari_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_gaara] ~~~ replaceitem entity @p slot.armor.feet 1 hair:gaara_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobirama] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobirama_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_boruto] ~~~ replaceitem entity @p slot.armor.feet 1 hair:boruto_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_mitsuki] ~~~ replaceitem entity @p slot.armor.feet 1 hair:mitsuki_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_tobi] ~~~ replaceitem entity @p slot.armor.feet 1 hair:tobi_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
dialogue open @s @p cor_vermelho"
execute @p[r=1,tag=cabelo_sakura] ~~~ replaceitem entity @p slot.armor.feet 1 hair:sakura_vermelho 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_hinata_2] ~~~ replaceitem entity @p slot.armor.feet 1 hair:hinata_vermelho_2 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}
execute @p[r=1,tag=cabelo_anko] ~~~ replaceitem entity @p slot.armor.feet 1 hair:anko_vermelho_2 1 0 {"item_lock":{"mode":"lock_in_inventory"},"keep_on_death":{}}