kill @e[type=item]
stopsound @p
clear @p
tag @p remove uchiha
tag @p remove uzumaki
tag @p remove hyuuga
tag @p remove chinoike
tag @p remove kazekage
tag @p remove senju
tag @p remove fogo
tag @p remove agua
tag @p remove vento
tag @p remove raio
tag @p remove terra
tag @p remove areia
tag @p remove areia_ferro
tag @p remove areia_ouro
tag @p remove ferro
tag @p remove gelo
tag @p remove lava
tag @p remove madeira
tag @p remove vapor
tag @p remove cristal
tag @p remove lama
tag @p remove tempestade
tag @p remove cabelo_naruto
tag @p remove cabelo_naruto_2
tag @p remove cabelo_naruto_3
tag @p remove cabelo_naruto_4
tag @p remove cabelo_sasuke
tag @p remove cabelo_sasuke_2
tag @p remove cabelo_sasuke_3
tag @p remove cabelo_sasuke_4
tag @p remove cabelo_sakura
tag @p remove cabelo_kakashi
tag @p remove cabelo_hinata
tag @p remove cabelo_jiraya
tag @p remove cabelo_itachi
tag @p remove cabelo_pain
tag @p remove cabelo_tobi
tag @p remove cabelo_deidara
tag @p remove cabelo_tenten
tag @p remove cabelo_temari
tag @p remove cabelo_madara
tag @p remove cabelo_gaara
tag @p remove cabelo_rockelee
tag @p remove cabelo_neji
tag @p remove cabelo_deidara
tag @p remove cabelo_mitsuki
tag @p remove cabelo_boruto
tag @p remove cabelo_tobirama
tag @p remove cabelo_minato
tag @p remove cabelo_tobirama
tag @p remove cabelo_anko
tag @p remove cabelo_hinata_2
tag @p remove menu
tag @p remove menu1
tag @p remove kurama
tag @p remove kurama_2
tag @p remove enfrentar_kurama
tag @p remove sharingan_2
tag @p remove sharingan_3
tag @p remove sharingan_m
tag @p remove sharingan_me
tag @p remove susanoo_1
tag @p remove susanoo_2
tag @p remove susanoo_3
tag @p remove susanoo_4
tag @p remove selar_minato
tag @p remove m_sharingan
tag @p remove ms_sasuke
tag @p remove ms_itachi
tag @p remove ms_madara
tag @p remove ms_shisui
tag @p remove ms_obito
tag @p remove msb_sasuke
tag @p remove msb_itachi
tag @p remove msb_madara
tag @p remove msb_shisui
tag @p remove msb_obito
tag @p remove rt_sasuke
tag @p remove rt_itachi
tag @p remove rt_madara
tag @p remove rt_shisui
tag @p remove rt_obito
tag @p remove s1_sasuke
tag @p remove s1_itachi
tag @p remove s1_madara
tag @p remove s1_shisui
tag @p remove s1_obito
tag @p remove s2_sasuke
tag @p remove s2_itachi
tag @p remove s2_madara
tag @p remove s2_shisui
tag @p remove s2_obito
tag @p remove s3_sasuke
tag @p remove s3_itachi
tag @p remove s3_madara
tag @p remove s3_shisui
tag @p remove s3_obito
tag @p remove s4_sasuke
tag @p remove s4_itachi
tag @p remove s4_madara
tag @p remove s4_shisui
tag @p remove s4_obito
tag @p remove kamui
tag @p remove kamui_1
tag @p remove shina_tem_c
tag @p remove rinnegan
tag @p remove byakugan
tag @p remove tenseigan
tag @p remove despertar_s
tag @p remove rinnegan_supremo
tag @p remove s1_susanoo
tag @p remove ss1_susanoo
tag @p remove s2_susanoo
tag @p remove ss2_susanoo
tag @p remove s3_susanoo
tag @p remove ss3_susanoo
tag @p remove s4_susanoo
tag @p remove ss4_susanoo
tag @p remove me_sharingan
tag @p remove mse_sharingan
tag @p remove ms_sharingan
tag @p remove byakugan
tag @p remove kazekage_inicio
tag @p remove hyuuga_inicio
tag @p remove uchiha_inicio
tag @p remove uzumaki_inicio
tag @p remove senju_inicio
tag @p remove chinoike_inicio
tag @p remove hagoromo
tag @p remove celula_hashirama
tag @p remove celulas_hashirama
tag @p remove jougan
tag @p remove tenseigan
tag @p remove boruto
tag @p remove ccc
tag @p remove jutsu1
tag @p remove jutsu2
tag @p remove jutsu3
tag @p remove jutsu4
tag @p remove jutsu5
tag @p remove elemento
tag @p remove cla
tag @p remove hair
tag @p remove mk1_kurama
tag @p remove mk3_kurama
tag @p remove mk1_shukaku
tag @p remove mk3_shukaku
tag @p remove shukaku
tag @p remove shukaku2
tag @p remove matatabi2
tag @p remove matatabi
tag @p remove batalha_shukaku
tag @p remove batalha_kurama
tag @p remove batalha_matatabi
tag @p remove kurama2
tag @p remove hyuugasenju
tag @p remove uchihahyuuga
tag @p remove hyuugauchiha
tag @p remove kazekage
tag @p remove areia_on
tag @p remove ouro_on
tag @p remove ferro_on
tag @p remove areia_ferro
tag @p remove areia_ouro
tag @p remove mk1_shukakua
tag @p remove mk1_kuramaa
tag @p remove kurama_selar
tag @p remove shukaku_selar
tag @p remove kamui
tag @p remove kamui1a
tag @p remove kamui2a
tag @p remove kamui3a
tag @p remove kamui_1
tag @p remove shinra
tag @p remove pergaminho
tag @p remove edotensei
tag @p remove olho
tag @p remove pele
tag @p remove cla
tag @p remove hair
tag @p remove claro
tag @p remove branco 
tag @p remove moreno
tag @p remove negro
tag @p remove escuro
tag @p remove mh1_naruto
tag @p remove mh2_naruto
tag @p remove mh3_naruto
tag @p remove mh4_naruto
tag @p remove mh5_naruto
tag @p remove mh6_naruto
tag @p remove mh7_naruto
tag @p remove mh8_naruto
tag @p remove mh9_naruto
tag @p remove mh10_naruto
tag @p remove mh11_naruto
tag @p remove mh12_naruto
tag @p remove mh13_naruto
tag @p remove mh14_naruto
tag @p remove mh15_naruto
tag @p remove mh16_naruto
tag @p remove mh17_naruto
tag @p remove mh18_naruto
tag @p remove mh19_naruto

tag @p remove mh1_sasuke
tag @p remove mh2_sasuke
tag @p remove mh3_sasuke
tag @p remove mh4_sasuke
tag @p remove mh5_sasuke
tag @p remove mh6_sasuke
tag @p remove mh7_sasuke
tag @p remove mh8_sasuke
tag @p remove mh9_sasuke
tag @p remove mh10_sasuke
tag @p remove mh11_sasuke
tag @p remove mh12_sasuke
tag @p remove mh13_sasuke
tag @p remove mh14_sasuke
tag @p remove mh15_sasuke
tag @p remove mh16_sasuke
tag @p remove mh17_sasuke
tag @p remove mh18_sasuke
tag @p remove mh19_sasuke

tag @p remove fala1
tag @p remove fala1_mh1
tag @p remove fala1_mh2
tag @p remove fala1_mh3
tag @p remove fala1_mh4
tag @p remove fala1_mh5
tag @p remove fala1_mh6
tag @p remove fala1_mh7
tag @p remove fala_iruka
tag @p remove mh_completo
tag @p remove golem
tag @p remove despertar_s
tag @p remove olho_vermelho
tag @p remove olho_amarelo
tag @p remove olho_verde
tag @p remove olho_azul
tag @p remove olho_preto
tag @p remove olho_branco
tag @p remove amaterasu1
tag @p remove amaterasu_katon
tag @p remove hair_kakashi
tag @p remove idade
tag @p remove idade1
tag @p remove idade1_
tag @p remove idade2
tag @p remove idade2_
tag @p remove idade3
tag @p remove idade2up
tag @p remove rank_d
tag @p remove rank_c
tag @p remove rank_b
tag @p remove rank_a
tag @p remove rank_s
tag @p remove msd_itachi
tag @p remove msd_madara
tag @p remove msd_obito
tag @p remove msd_shisui
tag @p remove msd_sasuke
tag @p remove fala1_mh1_sasuke
tag @p remove fala2_mh1_sasuke
tag @p remove fala3_mh1_sasuke
tag @p remove fala4_mh1_sasuke
tag @p remove fala5_mh1_sasuke
tag @p remove fala6_mh1_sasuke
tag @p remove fala7_mh1_sasuke
tag @p remove fala8_mh1_sasuke
tag @p remove fala9_mh1_sasuke
tag @p remove fala10_mh1_sasuke
tag @p remove fala11_mh1_sasuke
tag @p remove fala12_mh1_sasuke
tag @p remove fala_mh1_sasuke
tag @p remove fala1_mh8_sasuke
tag @p remove fala2_mh8_sasuke
tag @p remove fala3_mh8_sasuke
tag @p remove fala4_mh8_sasuke
tag @p remove fala5_mh8_sasuke
tag @p remove fala6_mh8_sasuke
tag @p remove fala7_mh8_sasuke
tag @p remove fala8_mh8_sasuke
tag @p remove fala9_mh8_sasuke
tag @p remove fala10_mh8_sasuke
tag @p remove fala11_mh1_sasuke
tag @p remove fala12_mh1_sasuke
tag @p remove chakra_bijuu
tag @p remove isshiki
tag @p remove hagoromo
tag @p remove sharingan
tag @p remove ccc
tag @p remove selamento
tag @p remove passe1
tag @p remove porkyn
tag @p remove karma_kawaki
tag @p remove karma_isshiki
tag @p remove otsutsuki
tag @p remove otsu
tag @p remove nuvem
tag @p remove folha
tag @p remove areia
tag @p remove pedra
tag @p remove nevoa
tag @p remove isshiki
tag @p remove 
tag @p remove 
tag @p remove 
playanimation @p animation.idade1 a 1
tag @p add rank_d
scoreboard players set @p chakra 1000
scoreboard players set @p tp 0
scoreboard players set @p xp 0
scoreboard players set @p money 0
scoreboard players set @p chakra_kurama 0
scoreboard players set @p subs 4
weather clear
time set day
effect @p clear
xp 0 @p
tellraw @p {"rawtext":[{"text":"§eVocê reiniciou!"}]}